apiVersion: v1
kind: PersistentVolume
metadata:
  name: webserver-pv 
  labels:
    component: nolimits
    function: www
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain 
  hostPath: 
    path: /opt/k8s/webserver
