apiVersion: v1
kind: PersistentVolume
metadata:
  name: webserver-pv 
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  hostPath: 
    path: /opt/k8s/webserver
