apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webserver-pvc
  labels:
    app: nolimits
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      component: nolimits
      function: www
