apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webserver-pvc
  labels:
    app: nolimits
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
